### ISSUE TITLE
Build failed on docs.rs

### ISSUE THREAD

**Issue by jerry73204** [antimatter15/tesseract-rs#13]
It was caused by missing headers according docs.rs log. Suppose we can add a feature to optionally enable binding generation to resolve this issue?

**Comment by ccouzens** [comment]
Hi @jerry73204 , would this work? I think if the underlying libraries don't build then tesseract-rs wouldn't build either. I'd be happy for you to show me how it would work.

I think another approach to getting docs.rs to build the docs, is to have `libleptonica-dev` and `libtesseract-dev` installed in docs.rs's virtual machine. I think they are taking pull requests. I might have another go of working out the process of getting it installed in their vagrant image.


---

Here are the build logs https://docs.rs/crate/tesseract/0.3.1/builds/208348

**Comment by ccouzens** [comment]
I'm not sure which change in which project fixed it, but the docs are now building on docs.rs.

https://docs.rs/tesseract/0.5.0/tesseract/fn.ocr.html

I'm going to improve the documentation in my refactor.
