### ISSUE TITLE
Support for init_1 constructor?

### ISSUE THREAD

**Issue by nico-abram** [antimatter15/tesseract-rs#28]
I think the init_1 constructor is the only one that supports constructing from an in-memory training data file. I really want to avoid the hassle of using a file and just want to use rust's include_bytes! macro and put it right in the binary. 

Maybe I misunderstood something, I've never used tesseract before, but this is the one I think I want:
![imagen](https://user-images.githubusercontent.com/24706838/146343275-c3f0c4d4-f7aa-45ab-bb17-63abadd52896.png)

I haven't found it in tesseract-sys yet, if someone could point me in the right direction I'd appreciate it, and I could maybe send a PR to add it to tesseract-rs.

**Comment by nico-abram** [comment]
Hi!

Thanks for the response. I'm not looking to set an *image* from memory, I want to set the *training data* from memory. It seems implicitly tesseract looks in ./tessdata/{lang}.traineddata . The init docs for tesseract I was looking at were these: https://tesseract-ocr.github.io/tessapi/5.x/a02438.html#a2be07b4c9449b8cfc43e9c26ee623050 . I think I got to that link from this lib's docs.

In tesseract-sys I found TessBaseAPIInit1 to TessBaseAPIInit4, but none seem to have the data and data_size parameters for the training data I'm interested in https://docs.rs/tesseract-sys/latest/tesseract_sys/fn.TessBaseAPIInit1.html . I must be missing something.

**Comment by nico-abram** [comment]
Aha! I think the initialization function I want is only available in the C++ API and not the C API:

It's here https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/baseapi.h#L220-L226

But not here https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/capi.h#L221-L235

So I'm not sure anything can be done about it. Maybe someone more experienced with tesseract than me can find a workaround

**Comment by ccouzens** [comment]
> I'm not looking to set an image from memory, I want to set the training data from memory.

Sorry for initially misunderstanding

> only available in the C++ API

> So I'm not sure anything can be done about it. Maybe someone more experienced with tesseract than me can find a workaround

We can technically create bindings to c++.

https://rust-lang.github.io/rust-bindgen/cpp.html#generating-bindings-to-c

I've created an issue in `tesseract-sys` to bind against more of the c++ API. https://github.com/ccouzens/tesseract-sys/issues/12 We already use the C++ API but only for some constants.
