### ISSUE TITLE
Compatibility with Tesseract 5.x?

### ISSUE THREAD

**Issue by Mek101** [antimatter15/tesseract-rs#29]
Is this crate compatible with Tesseract 5.0.0 and above?

**Comment by ccouzens** [comment]
Hi,

Yes, as of about a week ago tesseract-sys got updated which has made tesseract-rs (and leptess) compatible with tesseract 5.0.0.

https://github.com/ccouzens/tesseract-sys/pull/15

Let me know if you have any issues
