### ISSUE TITLE
Switch to bindgen

### ISSUE THREAD

**Issue by spacekookie** [antimatter15/tesseract-rs#3]
Using the [bindgen](https://github.com/rust-lang-nursery/rust-bindgen) crate via `build.rs` is a lot better for generating bindings these days.

**Comment by ccouzens** [comment]
@spacekookie , I've opened a pull request to switch to bindgen.

https://github.com/antimatter15/tesseract-rs/pull/5

This is my first time using bindgen. Is it possible for you to take a look?
I think it's generating functions for a lot of the c standard library. Do you know what I should be whitelisting or blacklisting? I see there is a guide about it, but I don't know what I should be whitelisting https://rust-lang.github.io/rust-bindgen/whitelisting.html

**Comment by ccouzens** [comment]
Tesseract 0.2.0 depends on leptonica-sys: 0.1.0 and tesseract-sys: 0.2.0.

Both these versions are generated using bindgen.
