### ISSUE TITLE
[Feature] Support setting segmentation mode

### ISSUE THREAD

**Issue by olalonde** [antimatter15/tesseract-rs#33]
E.g. `api->SetPageSegMode(tesseract::PSM_AUTO_OSD);` in https://tesseract-ocr.github.io/tessdoc/Examples_C++.html

**Comment by olalonde** [comment]
There's a `tessedit_pageseg_mode` which might do the same thing? For now using `.set_variable("tessedit_pageseg_mode", "10")` and hoping it is the same.

**Comment by ccouzens** [comment]
Hi, I might be able to get some time at the weekend to look into this.

Notes for myself:
https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/fn.TessBaseAPISetPageSegMode.html
https://tesseract-ocr.github.io/tessapi/5.x/a02438.html#a15a7a9c1afbba3078a55b4566de891ab
[TessPageSegMode_PSM_AUTO](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_AUTO.html)
[TessPageSegMode_PSM_AUTO_ONLY](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_AUTO_ONLY.html)
[TessPageSegMode_PSM_AUTO_OSD](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_AUTO_OSD.html)
[TessPageSegMode_PSM_CIRCLE_WORD](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_CIRCLE_WORD.html)
[TessPageSegMode_PSM_COUNT](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_COUNT.html)
[TessPageSegMode_PSM_OSD_ONLY](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_OSD_ONLY.html)
[TessPageSegMode_PSM_RAW_LINE](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_RAW_LINE.html)
[TessPageSegMode_PSM_SINGLE_BLOCK](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_BLOCK.html)
[TessPageSegMode_PSM_SINGLE_BLOCK_VERT_TEXT](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_BLOCK_VERT_TEXT.html)
[TessPageSegMode_PSM_SINGLE_CHAR](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_CHAR.html)
[TessPageSegMode_PSM_SINGLE_COLUMN](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_COLUMN.html)
[TessPageSegMode_PSM_SINGLE_LINE](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_LINE.html)
[TessPageSegMode_PSM_SINGLE_WORD](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SINGLE_WORD.html)
[TessPageSegMode_PSM_SPARSE_TEXT](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SPARSE_TEXT.html)
[TessPageSegMode_PSM_SPARSE_TEXT_OSD](https://docs.rs/tesseract-sys/0.5.14/tesseract_sys/constant.TessPageSegMode_PSM_SPARSE_TEXT_OSD.html)

**Comment by ccouzens** [comment]
> There's a `tessedit_pageseg_mode` which might do the same thing? For now using `.set_variable("tessedit_pageseg_mode", "10")` and hoping it is the same.

I think you're right about this. The [documentation](https://tesseract-ocr.github.io/tessapi/5.x/a02438.html#a15a7a9c1afbba3078a55b4566de891ab) says

> The mode is stored as an `IntParam` so it can also be modified by ReadConfigFile or `SetVariable("tessedit_pageseg_mode", mode as string)`.

**Comment by olalonde** [comment]
Cool, so I guess this API is not really necessary then.

**Comment by ccouzens** [comment]
None the less, I've made a PR

https://github.com/antimatter15/tesseract-rs/pull/36/files
